import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef } from "react";
import { BookOpen, ExternalLink, FileText, Code } from "lucide-react";

const publications = [
  {
    title: "PRO-V-R1: Reasoning Enhanced Programming Agent for RTL Verification",
    authors: "Yujie Zhao, Zhijing Wu, Boqin Yuan, Zhongming Yu, Hejia Zhang, Wentao Ni, Chia-Tung Ho, Haoxing Ren, Jishen Zhao",
    venue: "arXiv Preprint, 2025",
    tag: "Co-Author",
    links: {
      paper: "https://arxiv.org/abs/2506.12200",
    },
  },
  {
    title: "L-MARS: Legal Multi-Agent Workflow with Orchestrated Reasoning and Agentic Search",
    authors: "Ziqi Wang, Boqin Yuan",
    venue: "arXiv Preprint, 2025",
    tag: "Co-Author",
    links: {
      paper: "https://arxiv.org/abs/2509.00761",
    },
  },
  {
    title: "aiXiv: A Next-Generation Open Access Ecosystem for Scientific Discovery Generated by AI Scientists",
    authors: "Pengsong Zhang, Xiang Hu, Guowei Huang, Yang Qi, Heng Zhang, Boqin Yuan et al.",
    venue: "arXiv Preprint, 2025",
    tag: "Co-Author",
    links: {
      paper: "https://arxiv.org/abs/2508.15126",
    },
  },
];

const PublicationsSection = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  return (
    <section id="publications" className="py-24 bg-background">
      <div className="container mx-auto px-6" ref={ref}>
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="flex items-center gap-3 mb-8"
        >
          <div className="p-2 bg-accent rounded-lg">
            <BookOpen className="w-6 h-6 text-accent-foreground" />
          </div>
          <h2 className="section-heading">Publications</h2>
        </motion.div>

        <div className="space-y-6">
          {publications.map((pub, index) => (
            <motion.article
              key={pub.title}
              initial={{ opacity: 0, y: 30 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: 0.1 + index * 0.1 }}
              className="p-6 bg-card rounded-xl card-elevated group"
            >
              <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <span
                      className={`px-3 py-1 text-xs font-medium rounded-full ${
                        pub.tag === "First Author"
                          ? "bg-primary/10 text-primary"
                          : "bg-muted text-muted-foreground"
                      }`}
                    >
                      {pub.tag}
                    </span>
                    <span className="text-sm text-muted-foreground">
                      {pub.venue}
                    </span>
                  </div>
                  <h3 className="text-lg font-semibold text-foreground mb-2 group-hover:text-primary transition-colors">
                    {pub.title}
                  </h3>
                  <p className="text-muted-foreground text-sm">{pub.authors}</p>
                </div>

                <div className="flex items-center gap-3">
                  {pub.links.paper && (
                    <a
                      href={pub.links.paper}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 px-4 py-2 bg-muted rounded-lg text-sm font-medium text-foreground hover:bg-primary hover:text-primary-foreground transition-colors"
                    >
                      <FileText size={16} />
                      Paper
                    </a>
                  )}
                  {'code' in pub.links && (
                    <a
                      href={(pub.links as { paper: string; code?: string }).code}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-2 px-4 py-2 bg-muted rounded-lg text-sm font-medium text-foreground hover:bg-primary hover:text-primary-foreground transition-colors"
                    >
                      <Code size={16} />
                      Code
                    </a>
                  )}
                </div>
              </div>
            </motion.article>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ duration: 0.6, delay: 0.5 }}
          className="mt-8 text-center"
        >
          <a
            href="https://scholar.google.com/citations?user=AglrzBgAAAAJ&hl=en"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-primary hover:text-primary/80 font-medium transition-colors"
          >
            View all publications on Google Scholar
            <ExternalLink size={16} />
          </a>
        </motion.div>
      </div>
    </section>
  );
};

export default PublicationsSection;
